name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'guancan/md'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Debug Docker Credentials
      run: |
        echo "用户名存在校验: ${{ secrets.DOCKERHUB_USERNAME != null }}"
        echo "令牌存在校验: ${{ secrets.DOCKERHUB_TOKEN != null }}"
        echo "用户名长度: ${#DOCKERHUB_USERNAME}"
        echo "令牌长度: ${#DOCKERHUB_TOKEN}"
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build base image
      run: bash scripts/build-base-image.sh travor223/md

    - name: Build nginx image
      run: bash scripts/build-nginx.sh travor223/md

    - name: Build standalone image
      run: bash scripts/build-standalone.sh travor223/md

    - name: Build static image
      run: bash scripts/build-static.sh travor223/md

    - name: Push images to Docker Hub
      run: bash scripts/push-images.sh
